/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppPaymentsRouteImport } from './routes/_app/payments'
import { Route as AppPayoutsRouteImport } from './routes/_app/payouts'
import { Route as AppTradingAccountsRouteImport } from './routes/_app/trading-accounts'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as GuestSigninRouteImport } from './routes/_guest/signin'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppPayoutsRoute = AppPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AppRoute,
} as any)
const AppTradingAccountsRoute = AppTradingAccountsRouteImport.update({
  id: '/trading-accounts',
  path: '/trading-accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const GuestSigninRoute = GuestSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => GuestRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/payments': typeof AppPaymentsRoute
  '/payouts': typeof AppPayoutsRoute
  '/trading-accounts': typeof AppTradingAccountsRoute
  '/users': typeof AppUsersRoute
  '/signin': typeof GuestSigninRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/payments': typeof AppPaymentsRoute
  '/payouts': typeof AppPayoutsRoute
  '/trading-accounts': typeof AppTradingAccountsRoute
  '/users': typeof AppUsersRoute
  '/signin': typeof GuestSigninRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/payouts': typeof AppPayoutsRoute
  '/_app/trading-accounts': typeof AppTradingAccountsRoute
  '/_app/users': typeof AppUsersRoute
  '/_guest/signin': typeof GuestSigninRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/payments' | '/payouts' | '/trading-accounts' | '/users' | '/signin'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/payments' | '/payouts' | '/trading-accounts' | '/users' | '/signin'
  id:
    | '__root__'
    | '/_app'
    | '/_guest'
    | '/_app/payments'
    | '/_app/payouts'
    | '/_app/trading-accounts'
    | '/_app/users'
    | '/_guest/signin'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payouts': {
      id: '/_app/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof AppPayoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trading-accounts': {
      id: '/_app/trading-accounts'
      path: '/trading-accounts'
      fullPath: '/trading-accounts'
      preLoaderRoute: typeof AppTradingAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_guest/signin': {
      id: '/_guest/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof GuestSigninRouteImport
      parentRoute: typeof GuestRoute
    }
  }
}

interface AppRouteChildren {
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPayoutsRoute: typeof AppPayoutsRoute
  AppTradingAccountsRoute: typeof AppTradingAccountsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPaymentsRoute: AppPaymentsRoute,
  AppPayoutsRoute: AppPayoutsRoute,
  AppTradingAccountsRoute: AppTradingAccountsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface GuestRouteChildren {
  GuestSigninRoute: typeof GuestSigninRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestSigninRoute: GuestSigninRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
