/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBrokersRouteImport } from './routes/_app/brokers'
import { Route as AppFirmRouteImport } from './routes/_app/firm'
import { Route as AppPaymentsRouteImport } from './routes/_app/payments'
import { Route as AppPayoutsRouteImport } from './routes/_app/payouts'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppTradingAccountsRouteImport } from './routes/_app/trading-accounts'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as GuestSigninRouteImport } from './routes/_guest/signin'
import { Route as AppBrokersIndexRouteImport } from './routes/_app/brokers.index'
import { Route as AppBrokersIdRouteImport } from './routes/_app/brokers.$id'
import { Route as AppBrokersNewRouteImport } from './routes/_app/brokers.new'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products.index'
import { Route as AppProductsIdRouteImport } from './routes/_app/products.$id'
import { Route as AppProductsNewRouteImport } from './routes/_app/products.new'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBrokersRoute = AppBrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => AppRoute,
} as any)
const AppFirmRoute = AppFirmRouteImport.update({
  id: '/firm',
  path: '/firm',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppPayoutsRoute = AppPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppTradingAccountsRoute = AppTradingAccountsRouteImport.update({
  id: '/trading-accounts',
  path: '/trading-accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const GuestSigninRoute = GuestSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => GuestRoute,
} as any)
const AppBrokersIndexRoute = AppBrokersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBrokersRoute,
} as any)
const AppBrokersIdRoute = AppBrokersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppBrokersRoute,
} as any)
const AppBrokersNewRoute = AppBrokersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppBrokersRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppProductsIdRoute = AppProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/brokers': typeof AppBrokersRouteWithChildren
  '/firm': typeof AppFirmRoute
  '/payments': typeof AppPaymentsRoute
  '/payouts': typeof AppPayoutsRoute
  '/products': typeof AppProductsRouteWithChildren
  '/trading-accounts': typeof AppTradingAccountsRoute
  '/users': typeof AppUsersRoute
  '/signin': typeof GuestSigninRoute
  '/brokers/$id': typeof AppBrokersIdRoute
  '/brokers/new': typeof AppBrokersNewRoute
  '/products/$id': typeof AppProductsIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/brokers/': typeof AppBrokersIndexRoute
  '/products/': typeof AppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/firm': typeof AppFirmRoute
  '/payments': typeof AppPaymentsRoute
  '/payouts': typeof AppPayoutsRoute
  '/trading-accounts': typeof AppTradingAccountsRoute
  '/users': typeof AppUsersRoute
  '/signin': typeof GuestSigninRoute
  '/brokers/$id': typeof AppBrokersIdRoute
  '/brokers/new': typeof AppBrokersNewRoute
  '/products/$id': typeof AppProductsIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/brokers': typeof AppBrokersIndexRoute
  '/products': typeof AppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_app/brokers': typeof AppBrokersRouteWithChildren
  '/_app/firm': typeof AppFirmRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/payouts': typeof AppPayoutsRoute
  '/_app/products': typeof AppProductsRouteWithChildren
  '/_app/trading-accounts': typeof AppTradingAccountsRoute
  '/_app/users': typeof AppUsersRoute
  '/_guest/signin': typeof GuestSigninRoute
  '/_app/': typeof AppIndexRoute
  '/_app/brokers/$id': typeof AppBrokersIdRoute
  '/_app/brokers/new': typeof AppBrokersNewRoute
  '/_app/products/$id': typeof AppProductsIdRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/_app/brokers/': typeof AppBrokersIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brokers'
    | '/firm'
    | '/payments'
    | '/payouts'
    | '/products'
    | '/trading-accounts'
    | '/users'
    | '/signin'
    | '/brokers/$id'
    | '/brokers/new'
    | '/products/$id'
    | '/products/new'
    | '/brokers/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/firm'
    | '/payments'
    | '/payouts'
    | '/trading-accounts'
    | '/users'
    | '/signin'
    | '/brokers/$id'
    | '/brokers/new'
    | '/products/$id'
    | '/products/new'
    | '/brokers'
    | '/products'
  id:
    | '__root__'
    | '/_app'
    | '/_guest'
    | '/_app/brokers'
    | '/_app/firm'
    | '/_app/payments'
    | '/_app/payouts'
    | '/_app/products'
    | '/_app/trading-accounts'
    | '/_app/users'
    | '/_guest/signin'
    | '/_app/'
    | '/_app/brokers/$id'
    | '/_app/brokers/new'
    | '/_app/products/$id'
    | '/_app/products/new'
    | '/_app/brokers/'
    | '/_app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brokers': {
      id: '/_app/brokers'
      path: '/brokers'
      fullPath: '/brokers'
      preLoaderRoute: typeof AppBrokersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/firm': {
      id: '/_app/firm'
      path: '/firm'
      fullPath: '/firm'
      preLoaderRoute: typeof AppFirmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payouts': {
      id: '/_app/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof AppPayoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trading-accounts': {
      id: '/_app/trading-accounts'
      path: '/trading-accounts'
      fullPath: '/trading-accounts'
      preLoaderRoute: typeof AppTradingAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_guest/signin': {
      id: '/_guest/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof GuestSigninRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_app/brokers/': {
      id: '/_app/brokers/'
      path: '/'
      fullPath: '/brokers/'
      preLoaderRoute: typeof AppBrokersIndexRouteImport
      parentRoute: typeof AppBrokersRoute
    }
    '/_app/brokers/$id': {
      id: '/_app/brokers/$id'
      path: '/$id'
      fullPath: '/brokers/$id'
      preLoaderRoute: typeof AppBrokersIdRouteImport
      parentRoute: typeof AppBrokersRoute
    }
    '/_app/brokers/new': {
      id: '/_app/brokers/new'
      path: '/new'
      fullPath: '/brokers/new'
      preLoaderRoute: typeof AppBrokersNewRouteImport
      parentRoute: typeof AppBrokersRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/_app/products/$id': {
      id: '/_app/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AppProductsIdRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppProductsRoute
    }
  }
}

interface AppBrokersRouteChildren {
  AppBrokersIdRoute: typeof AppBrokersIdRoute
  AppBrokersNewRoute: typeof AppBrokersNewRoute
  AppBrokersIndexRoute: typeof AppBrokersIndexRoute
}

const AppBrokersRouteChildren: AppBrokersRouteChildren = {
  AppBrokersIdRoute: AppBrokersIdRoute,
  AppBrokersNewRoute: AppBrokersNewRoute,
  AppBrokersIndexRoute: AppBrokersIndexRoute,
}

const AppBrokersRouteWithChildren = AppBrokersRoute._addFileChildren(
  AppBrokersRouteChildren,
)

interface AppProductsRouteChildren {
  AppProductsIdRoute: typeof AppProductsIdRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppProductsRouteChildren: AppProductsRouteChildren = {
  AppProductsIdRoute: AppProductsIdRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppProductsRouteWithChildren = AppProductsRoute._addFileChildren(
  AppProductsRouteChildren,
)

interface AppRouteChildren {
  AppBrokersRoute: typeof AppBrokersRouteWithChildren
  AppFirmRoute: typeof AppFirmRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPayoutsRoute: typeof AppPayoutsRoute
  AppProductsRoute: typeof AppProductsRouteWithChildren
  AppTradingAccountsRoute: typeof AppTradingAccountsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBrokersRoute: AppBrokersRouteWithChildren,
  AppFirmRoute: AppFirmRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPayoutsRoute: AppPayoutsRoute,
  AppProductsRoute: AppProductsRouteWithChildren,
  AppTradingAccountsRoute: AppTradingAccountsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface GuestRouteChildren {
  GuestSigninRoute: typeof GuestSigninRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestSigninRoute: GuestSigninRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
